version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      PORT: 8000
    restart: unless-stopped

